=== dennysq/Documentacion/estudiantes.dtd
<!DOCTYPE Estudiante
[
<!ELEMENT Estudiante (cedula,nombre,masculino,fechaNacimiento?,ingresos?,asignaturas*)>
<!ELEMENT cedula (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT masculino (#PCDATA)>
<!ELEMENT fechaNacimiento (#PCDATA)>
<!ELEMENT ingresos(#PCDATA)>
<!ELEMENT asignaturas (codigo,nombre,creditos,aulas*)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT creditos(#PCDATA)>
<!ELEMENT aulas (codigo,ubicacion?)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT ubicacion (#PCDATA)>
]>

=== dennysq/Documentacion/Estudiante.xml
<?xml version="1.0" encoding="UTF-8" standalone= "yes"?>
<!DOCTYPE Estudiante SYSTEM "estudiantes.dtd">
<Estudiante xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="estudiantes.xsd">
<cedula>180144898e</cedula>
<nombre> Xavier</nombre>
<masculino> true </masculino>
<fechaNacimiento>1992-03-23</fechaNacimiento>
<ingresos>500.34</ingresos>
<asignaturas>
	<asignatura>
		<codigo>2</codigo>
		<nombre>algebra</nombre>
		
		<aulas>
			<aula>
				<codigo>B310</codigo>
				<ubicacion>Bloque B</ubicacion>
			</aula>
		</aulas>
	</asignatura>
</asignaturas>

</Estudiante>

=== dennysq/Documentacion/Estudiantes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Estudiantes SYSTEM "estudiantes.dtd"> 
<Estudiante xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="estudiantes.xsd">
  <cedula>1724170152</cedula>
  <nombre>Andres</nombre>
  <masculino>true</masculino>
  <fechaNacimiento>2002-09-24</fechaNacimiento>
  <ingresos>19.29</ingresos>
  <asignaturas>
      <asignatura>
        <codigo>1</codigo>
        <nombre>Arquitectura</nombre>
        <creditos>4</creditos>
        <aulas>
          <aula>
            <codigo>A1</codigo>
            <ubicacion>BLOQUE H200</ubicacion>
          </aula>
        </aulas>
      </asignatura>
  </asignaturas>  
</Estudiante>
